describe('finalizacaoDeCompra', () => {
    it('Validar ir até o fim do fluxo de compra já logado com um usuário', () => {
        //arrange
        cy.visit('https://magento.nublue.co.uk/')
        //act
        cy.get(':nth-child(6) > .product-item-info > .product-item-photo > .product-image-container > .product-image-wrapper > .product-image-photo').click()
        cy.get('#product-addtocart-button > span').click()
        cy.get('.message-success > div > a').click()
        cy.get('[class="grand totals"]')
        cy.wait(5)
        cy.get('[data-role="proceed-to-checkout"]').click()
        cy.get('[class="control _with-tooltip"]').click()
        cy.get('[type="email"]').eq(1).type('spinellibisneto@hotmail.com')
        cy.get('[name="firstname"]').type('Bruno')
        cy.get('[name="lastname"]').type('Spinelli')
        cy.get('[name="street[0]"]').type('Rua Augusta, 1503')
        cy.get('[name="country_id"]').select('Brazil')
        cy.get('[name="region_id"]').select('São Paulo')
        cy.get('[name="city"]').type('São Paulo')
        cy.get('[name="postcode"]').type('01305-100')
        cy.get('[name="telephone"]').type('11963770022')
        cy.get('[value="flatrate_flatrate"]').click()
        cy.get('[class="button action continue primary"]').click()
        cy.get('[placeholder="Enter discount code"]')
        cy.get('[title="Place Order"]').click()
        //assert
        cy.url().should('eq', 'https://magento.nublue.co.uk/checkout/onepage/success/')
        cy.get('[class="page-title"]').should('contain.text','Thank you for your purchase!')
        cy.get('[class="checkout-success"]').should('contain.text','Your order # is:')
        cy.get('[class="checkout-success"]').should('contain.text','We\'ll email you an order confirmation with details and tracking info.')
        cy.get('[href="https://magento.nublue.co.uk/"]').should('contain.text','Continue Shopping')
        cy.get('[href="https://magento.nublue.co.uk/checkout/account/delegateCreate/"]').should('contain.text','Create an Account')
    })
})